services:
  - type: web
    name: disease-prediction-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /
    plan: free